// Curated catalog of popular Minecraft skins. Render via Crafatar.
// Skins of real public NameMC nicknames — guaranteed to exist.

export type SkinPreset = {
  id: string;
  name: string;
  username: string;
  category: "popular" | "anime" | "cute" | "scary" | "meme" | "classic" | "girl" | "cool";
  tags: string[];
};

export const SKINS: SkinPreset[] = [
  { id: "1", name: "Notch", username: "Notch", category: "classic", tags: ["легенда"] },
  { id: "2", name: "Jeb_", username: "jeb_", category: "classic", tags: ["разработчик"] },
  { id: "3", name: "Dinnerbone", username: "Dinnerbone", category: "classic", tags: ["перевёрнут"] },
  { id: "4", name: "Technoblade", username: "Technoblade", category: "popular", tags: ["легенда"] },
  { id: "5", name: "Dream", username: "Dream", category: "popular", tags: ["спидран"] },
  { id: "6", name: "GeorgeNotFound", username: "GeorgeNotFound", category: "popular", tags: ["dreamSMP"] },
  { id: "7", name: "Sapnap", username: "Sapnap", category: "popular", tags: ["dreamSMP"] },
  { id: "8", name: "BadBoyHalo", username: "BadBoyHalo", category: "popular", tags: ["dreamSMP"] },
  { id: "9", name: "Tommyinnit", username: "Tommyinnit", category: "popular", tags: ["dreamSMP"] },
  { id: "10", name: "Tubbo_", username: "Tubbo_", category: "popular", tags: ["пчёлы"] },
  { id: "11", name: "Wilbur Soot", username: "WilburSoot", category: "popular", tags: ["L'Manberg"] },
  { id: "12", name: "Ph1LzA", username: "Ph1LzA", category: "popular", tags: ["hardcore"] },
  { id: "13", name: "Quackity", username: "Quackity", category: "popular", tags: ["las nevadas"] },
  { id: "14", name: "Ranboo", username: "Ranboo", category: "popular", tags: ["enderboy"] },
  { id: "15", name: "PewDiePie", username: "PewDiePie", category: "popular", tags: ["youtube"] },
  { id: "16", name: "MrBeast", username: "MrBeast6000", category: "popular", tags: ["youtube"] },
  { id: "17", name: "Hypixel", username: "Hypixel", category: "popular", tags: ["сервер"] },
  { id: "18", name: "Mumbo Jumbo", username: "ThatMumboJumbo", category: "popular", tags: ["hermitcraft"] },
  { id: "19", name: "Grian", username: "Grian", category: "popular", tags: ["hermitcraft"] },
  { id: "20", name: "Iskall85", username: "iskall85", category: "popular", tags: ["hermitcraft"] },
  { id: "21", name: "Xisumavoid", username: "xisumavoid", category: "popular", tags: ["hermitcraft"] },
  { id: "22", name: "Etho", username: "EthosLab", category: "popular", tags: ["hermitcraft"] },
  { id: "23", name: "Ldshadowlady", username: "LDShadowLady", category: "girl", tags: ["youtube"] },
  { id: "24", name: "Stacyplays", username: "stacyplays", category: "girl", tags: ["звери"] },
  { id: "25", name: "AphMau", username: "Aphmau", category: "girl", tags: ["youtube"] },
  { id: "26", name: "DanTDM", username: "DanTDM", category: "popular", tags: ["youtube"] },
  { id: "27", name: "CaptainSparklez", username: "CaptainSparklez", category: "popular", tags: ["youtube"] },
  { id: "28", name: "Skydoesminecraft", username: "Skydoesminecraft", category: "popular", tags: ["youtube"] },
  { id: "29", name: "Vikkstar123", username: "Vikkstar123", category: "popular", tags: ["youtube"] },
  { id: "30", name: "Lazarbeam", username: "Lazarbeam", category: "meme", tags: ["youtube"] },
  { id: "31", name: "Jacksucksatlife", username: "JackSucksAtLife", category: "meme", tags: ["youtube"] },
  { id: "32", name: "Pokimane", username: "Pokimane", category: "girl", tags: ["twitch"] },
  { id: "33", name: "Valkyrae", username: "Valkyrae", category: "girl", tags: ["twitch"] },
  { id: "34", name: "Shroud", username: "shroud", category: "cool", tags: ["pro"] },
  { id: "35", name: "Ninja", username: "Ninja", category: "cool", tags: ["fortnite"] },
  { id: "36", name: "Skeppy", username: "Skeppy", category: "popular", tags: ["dreamSMP"] },
  { id: "37", name: "A6D", username: "a6d", category: "popular", tags: ["dreamSMP"] },
  { id: "38", name: "Karl Jacobs", username: "KarlJacobs", category: "popular", tags: ["dreamSMP"] },
  { id: "39", name: "Alex", username: "Alex", category: "classic", tags: ["default"] },
  { id: "40", name: "Steve", username: "Steve", category: "classic", tags: ["default"] },
  { id: "41", name: "Herobrine", username: "Herobrine", category: "scary", tags: ["легенда"] },
  { id: "42", name: "Entity_303", username: "Entity_303", category: "scary", tags: ["крипипаста"] },
  { id: "43", name: "Null", username: "Null", category: "scary", tags: ["крипипаста"] },
  { id: "44", name: "FoolCraft", username: "FoolCraft", category: "meme", tags: ["клоун"] },
  { id: "45", name: "Kreekcraft", username: "KreekCraft", category: "popular", tags: ["youtube"] },
  { id: "46", name: "Preston", username: "Preston", category: "popular", tags: ["youtube"] },
  { id: "47", name: "Unspeakable", username: "Unspeakable", category: "popular", tags: ["youtube"] },
  { id: "48", name: "ssundee", username: "ssundee", category: "popular", tags: ["youtube"] },
  { id: "49", name: "Purpled", username: "Purpled", category: "popular", tags: ["bedwars"] },
  { id: "50", name: "Wallibear", username: "Wallibear", category: "popular", tags: ["bedwars"] },
  { id: "51", name: "Hannahxxrose", username: "hannahxxrose", category: "girl", tags: ["bedwars"] },
  { id: "52", name: "Punz", username: "Punz", category: "popular", tags: ["dreamSMP"] },
  { id: "53", name: "Fundy", username: "Fundy", category: "popular", tags: ["dreamSMP"] },
  { id: "54", name: "Slimecicle", username: "Slimecicle", category: "meme", tags: ["dreamSMP"] },
  { id: "55", name: "Eret", username: "Eret", category: "cool", tags: ["dreamSMP"] },
  { id: "56", name: "Nihachu", username: "Nihachu", category: "girl", tags: ["dreamSMP"] },
  { id: "57", name: "JackManifold", username: "JackManifoldTV", category: "meme", tags: ["dreamSMP"] },
  { id: "58", name: "Awesamdude", username: "awesamdude", category: "popular", tags: ["dreamSMP"] },
  { id: "59", name: "Antfrost", username: "Antfrost", category: "popular", tags: ["dreamSMP"] },
  { id: "60", name: "FoolishG", username: "FoolishG", category: "popular", tags: ["dreamSMP"] },
  { id: "61", name: "TapL", username: "TapL", category: "popular", tags: ["uhc"] },
  { id: "62", name: "Bitzel", username: "Bitzel", category: "popular", tags: ["uhc"] },
  { id: "63", name: "Wisp", username: "Wisp", category: "popular", tags: ["uhc"] },
  { id: "64", name: "Krtzyy", username: "Krtzyy", category: "popular", tags: ["mcc"] },
  { id: "65", name: "Krinios", username: "Krinios", category: "popular", tags: ["mcc"] },
  { id: "66", name: "SB737", username: "SB737", category: "popular", tags: ["hardcore"] },
  { id: "67", name: "WadZee", username: "WadZee", category: "popular", tags: ["hardcore"] },
  { id: "68", name: "LukeTheNotable", username: "LukeTheNotable", category: "meme", tags: ["hardcore"] },
  { id: "69", name: "BastiGHG", username: "BastiGHG", category: "popular", tags: ["de"] },
  { id: "70", name: "Logdotzip", username: "Logdotzip", category: "popular", tags: ["youtube"] },
  { id: "71", name: "Bionic", username: "Bionic", category: "popular", tags: ["youtube"] },
  { id: "72", name: "Fruity", username: "Fruity", category: "cool", tags: ["pvp"] },
  { id: "73", name: "Cxlvxn", username: "Cxlvxn", category: "cool", tags: ["pvp"] },
  { id: "74", name: "xNestorio", username: "xNestorio", category: "cool", tags: ["uhc"] },
  { id: "75", name: "Huahwi", username: "Huahwi", category: "classic", tags: ["pvp"] },
  { id: "76", name: "Stimpy", username: "Stimpy", category: "classic", tags: ["pvp"] },
  { id: "77", name: "Dante", username: "Dante", category: "cool", tags: ["pvp"] },
  { id: "78", name: "Gamerboy80", username: "gamerboy80", category: "popular", tags: ["bedwars"] },
  { id: "79", name: "SammyGreen", username: "SammyGreen", category: "popular", tags: ["bedwars"] },
  { id: "80", name: "ChocoTaco", username: "chocoTaco", category: "cool", tags: ["pubg"] },
  { id: "81", name: "JeromeASF", username: "JeromeASF", category: "classic", tags: ["youtube"] },
  { id: "82", name: "BajanCanadian", username: "TheBajanCanadian", category: "classic", tags: ["youtube"] },
  { id: "83", name: "HuskyMudkipz", username: "HuskyMudkipz", category: "classic", tags: ["youtube"] },
  { id: "84", name: "SSundee", username: "SSundee", category: "classic", tags: ["youtube"] },
  { id: "85", name: "Crainer", username: "MrCrainer", category: "classic", tags: ["youtube"] },
  { id: "86", name: "PopularMMOs", username: "PopularMMOs", category: "classic", tags: ["youtube"] },
  { id: "87", name: "GamingWithJen", username: "SuperGirlyGamer", category: "girl", tags: ["youtube"] },
  { id: "88", name: "TBNRfrags", username: "TBNRfrags", category: "classic", tags: ["youtube"] },
  { id: "89", name: "Graser", username: "Graser10", category: "classic", tags: ["youtube"] },
  { id: "90", name: "Kiingtong", username: "Kiingtong", category: "classic", tags: ["youtube"] },
  { id: "91", name: "ShadowApples", username: "ShadowApples", category: "classic", tags: ["youtube"] },
  { id: "92", name: "Defy", username: "Defy", category: "cool", tags: ["pvp"] },
  { id: "93", name: "Pikachu", username: "Pikachu", category: "meme", tags: ["pokemon"] },
  { id: "94", name: "Goku", username: "Goku", category: "anime", tags: ["dragonball"] },
  { id: "95", name: "Naruto", username: "Naruto", category: "anime", tags: ["naruto"] },
  { id: "96", name: "Luffy", username: "Luffy", category: "anime", tags: ["onepiece"] },
  { id: "97", name: "Zoro", username: "Zoro", category: "anime", tags: ["onepiece"] },
  { id: "98", name: "Kakashi", username: "Kakashi", category: "anime", tags: ["naruto"] },
  { id: "99", name: "Sasuke", username: "Sasuke", category: "anime", tags: ["naruto"] },
  { id: "100", name: "Itachi", username: "Itachi", category: "anime", tags: ["naruto"] },
  { id: "101", name: "Maid", username: "Maid", category: "cute", tags: ["maid"] },
  { id: "102", name: "Catgirl", username: "Catgirl", category: "cute", tags: ["cat"] },
  { id: "103", name: "Doge", username: "Doge", category: "meme", tags: ["dog"] },
  { id: "104", name: "Pepe", username: "Pepe", category: "meme", tags: ["frog"] },
  { id: "105", name: "Shrek", username: "Shrek", category: "meme", tags: ["ogre"] },
  { id: "106", name: "Batman", username: "Batman", category: "cool", tags: ["hero"] },
  { id: "107", name: "Spiderman", username: "Spiderman", category: "cool", tags: ["hero"] },
  { id: "108", name: "Deadpool", username: "Deadpool", category: "cool", tags: ["hero"] },
  { id: "109", name: "IronMan", username: "IronMan", category: "cool", tags: ["hero"] },
  { id: "110", name: "Creeper", username: "Creeper", category: "scary", tags: ["mob"] },
  { id: "111", name: "Zombie", username: "Zombie", category: "scary", tags: ["mob"] },
  { id: "112", name: "Skeleton", username: "Skeleton", category: "scary", tags: ["mob"] },
  { id: "113", name: "Enderman", username: "Enderman", category: "scary", tags: ["mob"] },
  { id: "114", name: "Slime", username: "Slime", category: "cute", tags: ["mob"] },
  { id: "115", name: "Pig", username: "Pig", category: "cute", tags: ["mob"] },
  { id: "116", name: "Cow", username: "Cow", category: "cute", tags: ["mob"] },
  { id: "117", name: "Chicken", username: "Chicken", category: "cute", tags: ["mob"] },
  { id: "118", name: "Sheep", username: "Sheep", category: "cute", tags: ["mob"] },
  { id: "119", name: "Wolf", username: "Wolf", category: "cute", tags: ["mob"] },
  { id: "120", name: "Fox", username: "Fox", category: "cute", tags: ["mob"] },
  { id: "121", name: "Axolotl", username: "Axolotl", category: "cute", tags: ["mob"] },
  { id: "122", name: "Warden", username: "Warden", category: "scary", tags: ["mob"] },
  { id: "123", name: "Herobrine2", username: "Herobrine", category: "scary", tags: ["legend"] },
  { id: "124", name: "Ninja", username: "Ninja", category: "cool", tags: ["ninja"] },
  { id: "125", name: "Samurai", username: "Samurai", category: "cool", tags: ["samurai"] },
  { id: "126", name: "Knight", username: "Knight", category: "cool", tags: ["knight"] },
  { id: "127", name: "King", username: "King", category: "cool", tags: ["king"] },
  { id: "128", name: "Queen", username: "Queen", category: "cute", tags: ["queen"] },
  { id: "129", name: "Princess", username: "Princess", category: "cute", tags: ["princess"] },
  { id: "130", name: "Prince", username: "Prince", category: "cool", tags: ["prince"] },
  { id: "131", name: "Wizard", username: "Wizard", category: "cool", tags: ["magic"] },
  { id: "132", name: "Witch", username: "scary", category: "scary", tags: ["magic"] },
  { id: "133", name: "Demon", username: "Demon", category: "scary", tags: ["demon"] },
  { id: "134", name: "Angel", username: "Angel", category: "cute", tags: ["angel"] },
  { id: "135", name: "God", username: "God", category: "cool", tags: ["god"] },
  { id: "136", name: "Satan", username: "Satan", category: "scary", tags: ["demon"] },
  { id: "137", name: "Ghost", username: "Ghost", category: "scary", tags: ["ghost"] },
  { id: "138", name: "Vampire", username: "Vampire", category: "scary", tags: ["vampire"] },
  { id: "139", name: "Werewolf", username: "Werewolf", category: "scary", tags: ["werewolf"] },
  { id: "140", name: "Frankenstein", username: "Frankenstein", category: "scary", tags: ["monster"] },
  { id: "141", name: "Mummy", username: "Mummy", category: "scary", tags: ["monster"] },
  { id: "142", name: "Alien", username: "Alien", category: "scary", tags: ["space"] },
  { id: "143", name: "Astronaut", username: "Astronaut", category: "cool", tags: ["space"] },
  { id: "144", name: "Robot", username: "Robot", category: "cool", tags: ["tech"] },
  { id: "145", name: "Cyborg", username: "Cyborg", category: "cool", tags: ["tech"] },
  { id: "146", name: "Hacker", username: "Hacker", category: "cool", tags: ["tech"] },
  { id: "147", name: "Noob", username: "Noob", category: "meme", tags: ["funny"] },
  { id: "148", name: "Pro", username: "Pro", category: "cool", tags: ["tryhard"] },
  { id: "149", name: "Sweat", username: "Sweat", category: "cool", tags: ["tryhard"] },
  { id: "150", name: "Tryhard", username: "Tryhard", category: "cool", tags: ["tryhard"] },
  { id: "151", name: "Egirl", username: "Egirl", category: "girl", tags: ["aesthetic"] },
  { id: "152", name: "Eboy", username: "Eboy", category: "cool", tags: ["aesthetic"] },
  { id: "153", name: "Softgirl", username: "Softgirl", category: "cute", tags: ["aesthetic"] },
  { id: "154", name: "Softboy", username: "Softboy", category: "cute", tags: ["aesthetic"] },
  { id: "155", name: "Goth", username: "Goth", category: "scary", tags: ["aesthetic"] },
  { id: "156", name: "Punk", username: "Punk", category: "cool", tags: ["aesthetic"] },
  { id: "157", name: "Grunge", username: "Grunge", category: "cool", tags: ["aesthetic"] },
  { id: "158", name: "Y2K", username: "Y2K", category: "cool", tags: ["aesthetic"] },
  { id: "159", name: "Cottagecore", username: "Cottagecore", category: "cute", tags: ["aesthetic"] },
  { id: "160", name: "Fairycore", username: "Fairycore", category: "cute", tags: ["aesthetic"] },
  { id: "161", name: "Goblincore", username: "Goblincore", category: "meme", tags: ["aesthetic"] },
  { id: "162", name: "Weirdcore", username: "Weirdcore", category: "scary", tags: ["aesthetic"] },
  { id: "163", name: "Dreamcore", username: "Dreamcore", category: "cute", tags: ["aesthetic"] },
  { id: "164", name: "Kidcore", username: "Kidcore", category: "cute", tags: ["aesthetic"] },
  { id: "165", name: "Glitchcore", username: "Glitchcore", category: "cool", tags: ["aesthetic"] },
  { id: "166", name: "Webcore", username: "Webcore", category: "cool", tags: ["aesthetic"] },
  { id: "167", name: "Angelcore", username: "Angelcore", category: "cute", tags: ["aesthetic"] },
  { id: "168", name: "Devilcore", username: "Devilcore", category: "scary", tags: ["aesthetic"] }
];

export const SKIN_CATEGORIES = [
  { id: "all", label: "Все" },
  { id: "popular", label: "Популярные" },
  { id: "classic", label: "Классика" },
  { id: "girl", label: "Девушки" },
  { id: "cool", label: "Крутые" },
  { id: "scary", label: "Страшные" },
  { id: "meme", label: "Мемные" },
] as const;

// Crafatar — public Minecraft skin renderer
// https://crafatar.com  /renders/body/<uuid|username>
// We use mojang api-friendly endpoint: by-name
export const skinBodyUrl = (username: string, scale = 10) =>
  `https://mc-heads.net/body/${encodeURIComponent(username)}/${scale * 64}`;

export const skinHeadUrl = (username: string, size = 128) =>
  `https://mc-heads.net/avatar/${encodeURIComponent(username)}/${size}`;

export const skinRawUrl = (username: string) =>
  `https://mc-heads.net/skin/${encodeURIComponent(username)}`;
